<a href="https://colab.research.google.com/github/AlenaAntipina/PutorchLearning/blob/firstTest/FirstPytorchTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones([3,4,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
torch.Tensor([[1,2,3,4], 
              [5,6,7,8,], 
              [9,10,11,12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x = torch.Tensor([[1,2,3,4], 
              [5,6,7,8,], 
              [9,10,11,12]])
x.size()

torch.Size([3, 4])

In [ ]:
x.shape()

TypeError: ignored

In [ ]:
x[0]

tensor([1., 2., 3., 4.])

In [ ]:
x[0, 1]

tensor(2.)

In [ ]:
x[:,0]

tensor([1., 5., 9.])

In [ ]:
x+10


tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [ ]:
x**2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [ ]:
x>4

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [ ]:
mask = x > 3

In [ ]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x[x>5]

tensor([ 6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).int()
limit = int(input())
larger_than_limit_sum = x[x>limit].sum()
print(larger_than_limit_sum)

5
tensor(30)


In [ ]:
x.dtype

torch.float32

In [ ]:
x = x.int()
print(x)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


In [ ]:
y = x.clone()
y[0,0] = 10
print(x)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
tensor([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]], dtype=torch.int32)


In [ ]:
import numpy as np
x = np.array([[1,2,3,4], [4,3,2,1]])
print(x)

[[1 2 3 4]
 [4 3 2 1]]


In [ ]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
z = torch.rand([2000,3000])
z

tensor([[0.7709, 0.6637, 0.8772,  ..., 0.1356, 0.0830, 0.7850],
        [0.7245, 0.1256, 0.1302,  ..., 0.7644, 0.7382, 0.8413],
        [0.2058, 0.2540, 0.2635,  ..., 0.8600, 0.2962, 0.4235],
        ...,
        [0.6163, 0.6943, 0.6255,  ..., 0.4025, 0.2055, 0.4212],
        [0.0839, 0.7051, 0.4689,  ..., 0.9866, 0.4071, 0.2395],
        [0.0747, 0.9424, 0.5137,  ..., 0.7883, 0.1574, 0.6428]])

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [ ]:
torch.device('cpu')

device(type='cpu')

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [ ]:
z_cuda = z.to(device)
z_cuda

tensor([[0.7709, 0.6637, 0.8772,  ..., 0.1356, 0.0830, 0.7850],
        [0.7245, 0.1256, 0.1302,  ..., 0.7644, 0.7382, 0.8413],
        [0.2058, 0.2540, 0.2635,  ..., 0.8600, 0.2962, 0.4235],
        ...,
        [0.6163, 0.6943, 0.6255,  ..., 0.4025, 0.2055, 0.4212],
        [0.0839, 0.7051, 0.4689,  ..., 0.9866, 0.4071, 0.2395],
        [0.0747, 0.9424, 0.5137,  ..., 0.7883, 0.1574, 0.6428]],
       device='cuda:0')

In [ ]:
%time w = (z - z + z * 10.0) ** 2

CPU times: user 14.9 ms, sys: 33.3 ms, total: 48.1 ms
Wall time: 47.6 ms


In [ ]:
%time w_cuda = (z_cuda - z_cuda + z_cuda * 10.0) ** 2

CPU times: user 1.66 ms, sys: 770 µs, total: 2.43 ms
Wall time: 2.81 ms
